### ISSUE TITLE
Missing DLL 

### ISSUE THREAD

**Issue by jsknnr** [niv/neverwinter.nim#1]
I have installed latest nim and included it in my environment variables. Build.cmd runs fine. When I try to run one of the commands I get this error:

could not load: pcre32.dll

This is on Windows 10.

Output of build:
```
PS C:\Users\John\Documents\NeverwinterNights_Projects\neverwinter_utils.nim> git pull --recurse-submodules --tags
Fetching submodule src/extlib/neverwinter.nim
Already up to date.
PS C:\Users\John\Documents\NeverwinterNights_Projects\neverwinter_utils.nim> .\build.cmd

C:\Users\John\Documents\NeverwinterNights_Projects\neverwinter_utils.nim>for %v in (src\*.nim) do nim -o:"bin\%~nv.exe" -d:release c "%v"

C:\Users\John\Documents\NeverwinterNights_Projects\neverwinter_utils.nim>nim -o:"bin\nwn_erf.exe" -d:release c "src\nwn_erf.nim"
Hint: used config file 'C:\Users\John\.choosenim\toolchains\nim-0.18.0\config\nim.cfg' [Conf]

C:\Users\John\Documents\NeverwinterNights_Projects\neverwinter_utils.nim>nim -o:"bin\nwn_gff.exe" -d:release c "src\nwn_gff.nim"
Hint: used config file 'C:\Users\John\.choosenim\toolchains\nim-0.18.0\config\nim.cfg' [Conf]

C:\Users\John\Documents\NeverwinterNights_Projects\neverwinter_utils.nim>nim -o:"bin\nwn_key_pack.exe" -d:release c "src\nwn_key_pack.nim"
Hint: used config file 'C:\Users\John\.choosenim\toolchains\nim-0.18.0\config\nim.cfg' [Conf]

C:\Users\John\Documents\NeverwinterNights_Projects\neverwinter_utils.nim>nim -o:"bin\nwn_key_shadows.exe" -d:release c "src\nwn_key_shadows.nim"
Hint: used config file 'C:\Users\John\.choosenim\toolchains\nim-0.18.0\config\nim.cfg' [Conf]

C:\Users\John\Documents\NeverwinterNights_Projects\neverwinter_utils.nim>nim -o:"bin\nwn_key_transparent.exe" -d:release c "src\nwn_key_transparent.nim"
Hint: used config file 'C:\Users\John\.choosenim\toolchains\nim-0.18.0\config\nim.cfg' [Conf]

C:\Users\John\Documents\NeverwinterNights_Projects\neverwinter_utils.nim>nim -o:"bin\nwn_key_unpack.exe" -d:release c "src\nwn_key_unpack.nim"
Hint: used config file 'C:\Users\John\.choosenim\toolchains\nim-0.18.0\config\nim.cfg' [Conf]

C:\Users\John\Documents\NeverwinterNights_Projects\neverwinter_utils.nim>nim -o:"bin\nwn_net.exe" -d:release c "src\nwn_net.nim"
Hint: used config file 'C:\Users\John\.choosenim\toolchains\nim-0.18.0\config\nim.cfg' [Conf]
lib\pure\asyncnet.nim(150, 7) Warning: Cannot prove that 'result' is initialized. This will become a compile time error in the future. [ProveInit]

C:\Users\John\Documents\NeverwinterNights_Projects\neverwinter_utils.nim>nim -o:"bin\nwn_resman_cat.exe" -d:release c "src\nwn_resman_cat.nim"
Hint: used config file 'C:\Users\John\.choosenim\toolchains\nim-0.18.0\config\nim.cfg' [Conf]

C:\Users\John\Documents\NeverwinterNights_Projects\neverwinter_utils.nim>nim -o:"bin\nwn_resman_diff.exe" -d:release c "src\nwn_resman_diff.nim"
Hint: used config file 'C:\Users\John\.choosenim\toolchains\nim-0.18.0\config\nim.cfg' [Conf]

C:\Users\John\Documents\NeverwinterNights_Projects\neverwinter_utils.nim>nim -o:"bin\nwn_resman_extract.exe" -d:release c "src\nwn_resman_extract.nim"
Hint: used config file 'C:\Users\John\.choosenim\toolchains\nim-0.18.0\config\nim.cfg' [Conf]

C:\Users\John\Documents\NeverwinterNights_Projects\neverwinter_utils.nim>nim -o:"bin\nwn_resman_grep.exe" -d:release c "src\nwn_resman_grep.nim"
Hint: used config file 'C:\Users\John\.choosenim\toolchains\nim-0.18.0\config\nim.cfg' [Conf]

C:\Users\John\Documents\NeverwinterNights_Projects\neverwinter_utils.nim>nim -o:"bin\nwn_resman_pkg.exe" -d:release c "src\nwn_resman_pkg.nim"
Hint: used config file 'C:\Users\John\.choosenim\toolchains\nim-0.18.0\config\nim.cfg' [Conf]

C:\Users\John\Documents\NeverwinterNights_Projects\neverwinter_utils.nim>nim -o:"bin\nwn_resman_stats.exe" -d:release c "src\nwn_resman_stats.nim"
Hint: used config file 'C:\Users\John\.choosenim\toolchains\nim-0.18.0\config\nim.cfg' [Conf]

C:\Users\John\Documents\NeverwinterNights_Projects\neverwinter_utils.nim>nim -o:"bin\nwn_tlk.exe" -d:release c "src\nwn_tlk.nim"
Hint: used config file 'C:\Users\John\.choosenim\toolchains\nim-0.18.0\config\nim.cfg' [Conf]

C:\Users\John\Documents\NeverwinterNights_Projects\neverwinter_utils.nim>nim -o:"bin\nwn_twoda.exe" -d:release c "src\nwn_twoda.nim"
Hint: used config file 'C:\Users\John\.choosenim\toolchains\nim-0.18.0\config\nim.cfg' [Conf]

C:\Users\John\Documents\NeverwinterNights_Projects\neverwinter_utils.nim>nim -o:"bin\packets.exe" -d:release c "src\packets.nim"
Hint: used config file 'C:\Users\John\.choosenim\toolchains\nim-0.18.0\config\nim.cfg' [Conf]
```
Output of attempting to run a command:
```
PS C:\Users\John\Documents\NeverwinterNights_Projects\neverwinter_utils.nim> nwn_resman_pkg -h
could not load: pcre32.dll
```

**Comment by dom96** [comment]
You can grab this DLL here: https://nim-lang.org/download/dlls.zip

**Comment by jsknnr** [comment]
That seems to fix the issue.

**Comment by niv** [comment]
For the record, new download should include all the needed dlls on Windows.

**Comment by Mingun** [comment]
Unfortunately, the problem still is present. The solution according to the link is higher too unclear -- where to place the downloaded dll?

I use Windows 10 x64 and try setup NWN dev environment as described in https://github.com/jakkn/nwn-devbase. I install
1. Ruby: https://github.com/oneclick/rubyinstaller2/releases/download/rubyinstaller-2.5.3-1/rubyinstaller-2.5.3-1-x64.exe
2. Nim (strange, but for windows only x86 prebuilt): https://github.com/dom96/choosenim/releases/download/v0.3.2/choosenim-0.3.2_windows_i386.exe
3. Install this package
    ```
    nimble install neverwinter
    ```
4. Install nwn-devbase
    ```sh
    git clone https://github.com/jakkn/nwn-devbase.git
    cd nwn-devbase
    gem install bundler
    bundle install
    ```
5. Download NWN Script Compiler: https://neverwintervault.org/sites/neverwintervault.org/files/project/29016/files/nwnsc-windows-1.0.0.zip
5. Create my NWN module devel folder:
    ```sh
    mkdir module && cd module
    git init
    ..\..\nwn-devbase\build.rb init
    cp path-to-my/module.mod server/modules/
    ```
6. Try to extract my `.mod` and get this error:
    ```sh
    D:\Projects\NWN\modules\module>..\..\nwn-devbase\build.rb -v extract
    [DEBUG] Current environment:
      FLAT_LAYOUT: false
      START_TIME: 2018-12-30 20:31:31 +0500
      ARGV: ["extract"]
      EXECUTION_DIR: D:/Projects/NWN/nwn-devbase
      WORKING_DIR: D:/Projects/NWN/modules/module
      NWNPROJECT: D:\Projects\NWN\modules\module\.nwnproject
      PROJECT_ROOT: D:\Projects\NWN\modules\module
      PROJECT_USER_CONFIG:
      PROJECT_DEFAULT_CONFIG: D:\Projects\NWN\modules\module\.nwnproject\config.rb.in
      GLOBAL_USER_CONFIG:
      GLOBAL_DEFAULT_CONFIG: D:\Projects\NWN\nwn-devbase\config.rb.in
      HOME_DIR: D:\Projects\NWN\modules\module\server
      INSTALL_DIR:
      MODULE_DIR: D:\Projects\NWN\modules\module\server\modules
      MODULE_FILENAME: module
      MODULE_FILE_EXT: .mod
      MODULE_FILE: D:/Projects/NWN/modules/module/server/modules/module.mod
      CACHE_DIR: D:\Projects\NWN\modules\module\.nwnproject\cache
      TMP_CACHE_DIR: D:\Projects\NWN\modules\module\.nwnproject\cache\tmp
      GFF_CACHE_DIR: D:\Projects\NWN\modules\module\.nwnproject\cache\gff
      SRC_DIR: D:\Projects\NWN\modules\module\src
      NUMBER_OF_SOURCES: 0
      NSS_DIR: D:\Projects\NWN\modules\module\src\nss
      NSS_BATCHOUTDIR: D:\Projects\NWN\modules\module\.nwnproject\cache\gff
      NSS_COMPILER: nwnsc
      COMPILER_ARGS: ["-qo", "-n", "", "-y", "-b", "D:\\Projects\\NWN\\modules\\module\\.nwnproject\\cache\\gff"]
      ERF_UTIL: nwn_erf
      GFF_UTIL: nwn-gff
      RESMAN_DIR: D:\Projects\NWN\modules\module\resman
      EXTRACT_RAKE: D:\Projects\NWN\nwn-devbase\extract.rake
      PACK_RAKE: D:\Projects\NWN\nwn-devbase\pack.rake
      SYMLINK_RAKE: D:\Projects\NWN\nwn-devbase\symlink.rake
      SCRIPTS_DIR: D:\Projects\NWN\nwn-devbase\scripts
    [INFO] Extracting D:/Projects/NWN/modules/module/server/modules/module.mod.
    could not load: pcre32.dll
    [ERROR] Something went wrong while extracting D:/Projects/NWN/modules/module/server/modules/module.mod.
    [ERROR] Aborting.
    ```
Can @niv or @jakkn tell me what I'm doing wrong and how to fix this?

**Comment by Mingun** [comment]
Ok, I finded place to where put downloaded dlls:
```sh
D:\Projects\NWN\modules\module>where nim
C:\Users\Mingun\.nimble\bin\nim.exe
```
and place it to `C:\Users\Mingun\.nimble\bin` and after that everything work. However I want to find the correct way of fix error

**Comment by jakkn** [comment]
I'll chime in here since I was mentioned and I have time to help out, @Mingun, but I have to say that this report is very confusing and I feel a need to start by saying why.

First, you are currently commenting on a closed issue about missing DLLs in the neverwinter.nim project whereas you're probably better off starting a new one. Second, the context is expanded to include nwn-devbase, which, although a consumer of neverwinter.nim, is a different project and not related to the topic. Third, by including all the instructions from the devbase readme, which has really nothing to do with the error, it's even harder to get a clear picture.

Now, from what I understand you are looking for the correct way to install the neverwinter.nim binaries on your Windows system - is that correct? If yes, then this is already [documented in the README](https://github.com/niv/neverwinter.nim/blob/master/README.md#just-static-binaries-please).
```
Binary releases are available on the Github Releases page of this project. You do not need to install anything else.
```
So grab the [latest release](https://github.com/niv/neverwinter.nim/releases) and put the binaries on your PATH environment variable. If you wish to build the binaries from sources you'll have to follow the documentation and put the contents of the /bin folder on your PATH environment variable.

I hope that clears things up.

**Comment by Mingun** [comment]
> First, you are currently commenting on a closed issue about missing DLLs in the neverwinter.nim project whereas you're probably better off starting a new one.

In the presence of an opportunity I always try to reopen old problems, than to get new, especially if old were not resolved in any specific way. In this case the task is simply closed without explanation that was changed that suggests me an idea that the author just could not reproduce it in their environment. In this case it seemed to me that the problem is not solved and there is a sense to open it and to continue work on its solution. Just GitHub does not give me of technical capability to reopen issue, otherwise I would make it.

> Second, the context is expanded to include nwn-devbase, which, although a consumer of neverwinter.nim, is a different project and not related to the topic.

The context is expanded for a demonstration of process in which the problem is reproduced. As I already wrote above, it seems, that the author just could not reproduce it and thought that the problem is solved. I show that it not so

> Third, by including all the instructions from the devbase readme, which has really nothing to do with the error, it's even harder to get a clear picture.

As I already stated above, these are full instructions for reproduction of an error. Perhaps, some of them excessive, but it is difficult to me to define it as neither Ruby, nor Nim are my main tools and are necessary to me only so far as they are required for `nwn-devbase`

> Now, from what I understand you are looking for the correct way to install the neverwinter.nim binaries on your Windows system - is that correct?

Yes, everything is correct

> If yes, then this is already documented in the README.

Hm. On me, this line does not look binding. More likely, as ONE of options:

    -- Hey, I do not want to potter with any installers, do you have just binaries?
    -- Yes, they here

And further there is the second option:

    -- And if I want to make everything correctly?
    -- Well, then here so

If it not that it is expected, it definitely it is worth reformulating

> I hope that clears things up.

Many thanks, @jakkn. Yes, all this places on the places.

----

@niv, thus, perhaps there is only a problem with insufficiently accurate documentation

**Comment by Mingun** [comment]
I will a little explain why installation of binary files seems hackish made especially for those who do not want to penetrate deeply. In the description of the `nwn-devbase` installation it is told that at first it is necessary to install `choosenim`, and then `newerwinter.nim`. If `newerwinter.nim` is delivered in binary files (i.e. it is supposed that this completely packed application without third-party dependences), then why Nim is required? Therefore, if it is required, installation of binary files is hack bypassing the package manager of Nim and it should be avoided
