### ISSUE TITLE
scriptcomp: Support raw and multi-line string literals

### ISSUE THREAD

**Issue by mtijanic** [niv/neverwinter.nim#52]
Currently, the way to write multiline string literals is basically:
```C
string s = "Hello, \n" +
                "World!\n";
```
which is both cumbersome to write and incurs a runtime cost as the concatenation happens when the script is loaded (see also #51). Proposing a new syntax for multiline raw literals.

I already have a patch that supports the following syntax:
```C#
string s = @"AAAAAA
BBBBB
  CCCCC
DD\nEE\x50FF\\


GGGGGG ""hello"" GGGGG\\


";
```
This is basically exactly the same as C# verbatim strings: All characters in `@"..."` block are treated literally, including new lines and backslashes. Only `""` has a special meaning in that it doesn't close the literal, but is interpreted as a single `"`. 

I guess consider this issue an RFC for the syntax.

**Comment by WilliamDraco** [comment]
Lifting from Nim, which has has `r"..."` blocks similar to this, another option could be triple-quoted blocks `"""..."""`, which has no exceptions (not even `""` as above).
Don't feel strongly either way personally.

**Comment by squattingmonk** [comment]
I'm also partial to the `"""..."""` syntax.

**Comment by mtijanic** [comment]
I think there's two separate things. Traditionally, `"""` is used for multiline strings - same as regular ones, but can take a newline character. In such strings, escape sequences such as `\x07` work fine (but single quote needn't be escaped as it's not ambiguous anymore).

Raw or verbatim strings disable all escapes and everything is taken exactly as written. These are traditionally written as `@"..."` or `r"..."`

Many languages (e.g. C++; even C# up until last year) don't have multiline non-raw strings. I'm not sure if nwscript needs them.

**Comment by mtijanic** [comment]
As fpr the syntax, I went with C# version as that's already syntactically close to nwscript. If we pull nim-isms chances are we'll hit issues down the road because the nim feature might have been designed with nim syntax in mind anf doesn't translate well to something with no significant whitespace.

Although C++ is now using `R"..."` so I can hope they thought it through and foresaw no issues.

Implementation-wise, `"""` is a bit harder as the parser only looks one character ahead, but not a huge deal.

**Comment by Daztek** [comment]
I don't care much about the syntax, so `@` seems fine to me. It'll be nice to to write sql queries without a million string concats.

**Comment by niv** [comment]
One concern I have about this improvement is that it takes up the `@` symbol, which we might want to use for something more idiomatic to NWN (e.g. object lookup or something),  similar to the idea to use `$` for stringification.

@ is a very reasonable symbol to have for "addressing", which I think is poor fit for multiline strings and a better fit elsewhere. Just because C# does it is no good reason to take the valuable symbol out of the available pool for cool future features.

**Comment by mtijanic** [comment]
That's a valid concern. I can change it to `r"..."` or `R"..."` instead if there's consensus.

**Comment by mtijanic** [comment]
Although, technically, it only takes up the `@"` digraph. `@n` is still available, as is `@s` or even `@ "foo"`. But if consensus says `r"..."` I'm fine with it.

**Comment by varenx** [comment]
I really like the idea of using `r"..."`, with nim having the same syntax and the compiler being part of the neverwinter.nim package, it carries that familiarity for people who work with nim themselves. And it's close enough to C++ too. :smile:

**Comment by niv** [comment]
I'd also be happy with seeing `r".."` here (maybe `m" .. "` can be multiline in the future to avoid the extra work of supporting `"""`).

**Comment by fvinke** [comment]
In the case of not using the @" digraph, I'd personally prefer to see R" over r". While it sounds like a minor difference, the odds of someone having been exposed to using R" over r" in his life would be biased into the direction of R". Not only due to the fact that exposure to C++ is substantially more likely than to nim, but also due to the fact that when you write NWScript you're probably more likely associating language features to C++ than you are to nim. If you're trying to jog your memory for a feature, you will think about the C school of languages. Especially for a standard user that is more likely to know about NWNX than the language tools in this repository are written in.

I can imagine myself frequently running into a compilation error where I use R" where r" is expected as linters and general tooling for NWScript is not quite at the level of a more widely used language, especially now that it is a moving target to write tooling for.

**Comment by mtijanic** [comment]
How about either r or R? 😸
